/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.benjamin.comscore;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.comscore.Analytics;
import com.comscore.PublisherConfiguration;


@Kroll.module(name="TitaniumcomscoreAndroid", id="com.benjamin.comscore")
public class TitaniumcomscoreAndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumcomscoreAndroidModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TitaniumcomscoreAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.i(LCAT, "comScore module created");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void startComScore(String pubID, String pubSecret) {
		Log.i(LCAT, "pubID: " + pubID + " pubSecret: " + pubSecret);
		
		PublisherConfiguration myPublisherConfig = new PublisherConfiguration.Builder()
	 	.publisherId( pubID ) // Provide your Publisher ID.
	 	.publisherSecret( pubSecret ) // Provide your Publisher Secret.
	 	.build();
	Analytics.getConfiguration().addClient( myPublisherConfig );
	Analytics.start( getActivity().getApplicationContext()  );
	Log.i(LCAT, "comScore module started");
	}
}

